<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerChlmloi\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerChlmloi/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerChlmloi.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerChlmloi\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerChlmloi\srcDevDebugProjectContainer([
    'container.build_hash' => 'Chlmloi',
    'container.build_id' => 'dafa4425',
    'container.build_time' => 1556283249,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerChlmloi');
